version: "3.1"
services:
  rest-sgd-integracion:
    build: .
    image: sigedin/rest-integracion
    container_name: rest-sgd-integracion
    restart: unless-stopped
    ports:
      - ${PORT}:${PORT}
    environment:
      PORT: ${PORT}
      NODE_ENV: ${NODE_ENV}